# Project information
site_name: CnOCR
site_url: https://cnocr.readthedocs.io
site_description: CnOCR ä½¿ç”¨è¯´æ˜æ–‡æ¡£
site_author: Breezedeus

# Repository
repo_url: https://github.com/breezedeus/cnocr
repo_name: Breezedeus/CnOCR
edit_uri: "" #disables edit button

# Copyright
copyright: Copyright &copy; 2021 - 2022

# Social media
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/breezedeus
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/breezedeus-50
    - icon: fontawesome/brands/youtube
      link: https://space.bilibili.com/509307267
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/breezedeus

# Configuration
theme:
  name: material
#  name: readthedocs
  logo: figs/breezedeus.png
  favicon: figs/breezedeus.ico
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition # alerts
  - pymdownx.details #  collapsible alerts
  - pymdownx.superfences # nest code and content inside alerts
  - attr_list # add HTML and CSS to Markdown elements
  - md_in_html
  - pymdownx.inlinehilite # inline code highlights
  - pymdownx.keys # show keystroke symbols
  - pymdownx.snippets # insert content from other files
  - pymdownx.tabbed # content tabs
  - footnotes
  - def_list
  - pymdownx.arithmatex: # mathjax
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      toc_depth: 4

# Plugins
plugins:
  - search
  - macros
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: false
            show_source: true
            show_category_heading: true
      watch:
        - cnocr

# Extra CSS
extra_css:
  - static/css/custom.css

# Extra JS
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - é¦–é¡µ: index.md
  - è¯¦ç»†æ–‡æ¡£:
      - ğŸ› ï¸ å®‰è£…: install.md
      - ğŸ“– ä½¿ç”¨è¯´æ˜: usage.md
      - ğŸ›€ğŸ» åœ¨çº¿Demo: demo.md
      - ğŸ„ğŸ» â€ï¸å‘½ä»¤è¡Œå·¥å…·: command.md
      - ğŸ¤¼â€ï¸ï¸ åˆ†ç±»æ¨¡å‹å·¥å…·: clf_command.md
      - ğŸ§³ å¯ç”¨æ¨¡å‹: models.md
      - ğŸ•¹ æ¨¡å‹è®­ç»ƒ: train.md
      - ğŸ“¡ OCRæŠ€æœ¯ä»‹ç»: std_ocr.md
      - ğŸ’¬ äº¤æµç¾¤: contact.md
      - ğŸ¥¤ ç»™ä½œè€…åŠ æ²¹: buymeacoffee.md
      - ğŸ™‹ğŸ½ å¸¸è§é—®é¢˜ï¼ˆFAQï¼‰: faq.md
      - ğŸ—’ RELEASEè¯´æ˜: RELEASE.md
  - æ¥å£è¯´æ˜:
    - CnOcr ç±»: cnocr/cn_ocr.md
    - Recognizer ç±»: cnocr/recognizer.md
    - ppocr.PPRecognizer ç±»: cnocr/pp_recognizer.md
